# This Ansible Dynamic inventory configuration for AWS is partially inspired by the following link:
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
plugin: aws_ec2

# Select all VMs in Frankfurt region
regions:
  - eu-central-1

# Select all hosts with ManagedBy "Ansible" tag
filters:
  tag:ManagedBy: Ansible
