# This file inspired by https://antonputra.com/helm-3-secrets-tutorial/
apiVersion: v1
kind: Secret
metadata:
  name: app-python-secret
  labels:
    app: app-python
type: Opaque
data:
  password: {{ .Values.secrets.password | b64enc | quote }}
