version: '3'

services:
  app_python:
    container_name: app_python
    image: "unaimillan/devops-app_python"
    ports:
      - "5000:5000"
    mem_limit: "512m"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
#    environment:
#      GF_SERVER_DOMAIN: "localhost"
#      GF_SERVER_ROOT_URL: "5000"
    user: "1000"
#    depends_on:
#      - prometheus
    networks:
      - monitoring
    mem_limit: "512m"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki:/etc/loki
      - loki:/data/loki:ro
    networks:
      - monitoring
    mem_limit: "512m"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "127.0.0.1:9080:9080"
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail:/etc/promtail-config/:ro
    command: -config.file=/etc/promtail-config/promtail.yml
    networks:
      - monitoring
    mem_limit: "512m"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=14d'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.wal-compression'
      - '--storage.tsdb.max-block-duration=4h'
      - '--storage.tsdb.wal-segment-size=60MB'
      - '--storage.tsdb.allow-overlapping-blocks'
      - '--query.max-samples=5000000'
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - monitoring
    mem_limit: "512m"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  monitoring:

volumes:
  grafana:
  loki:
  prometheus:
